#!/bin/sh
uci set wireless.radio0.disabled='0'
uci set wireless.radio1.disabled='0' 2>/dev/null
uci set wireless.default_radio0.ssid='OpenWrt_HG680p'
uci set wireless.default_radio0.encryption='none'
uci commit wireless
wifi reload
exit 0
